### ISSUE TITLE
Логгирование проекта

### ISSUE THREAD

**Issue by SidVeld** [Project-Frogger/Scraper#4]
# Без логов нам будет тяжело в будущем

Логирование нам точно понадобится в будущем, так как работа проекта должна стать практически автоматизированной. С логами нам будет куда проще следить за ходом работы парсера, скриптов и так далее.

# Задачи

В ходе закрытия этой темы нужно сделать несколько вещей

- [ ] Создать логгирование непосредственно в лог-файлы для локального хранения
- [ ] Сделать возможность загружать логи в специализированную базу данных

**Comment by elena-mayorova** [comment]
База под логи: `frogger_logs`

Таблица: `logs`

Поля:

- `log_id` (автоматическое)
- `log_lvl` - уровень лога (тип - строка длиной до 20 символов)
- `log_msg` - содержимое лога (тип - строка, ограничений по длине нет)
- `log_dttm` - дата и время лога, формат `YYYY-MM-DD hh:mm:ss`
